[package]
name = "metorex-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "metorex"
path = "src/main.rs"

[dependencies]
metorex-core = { path = "../core" }
metorex-runtime = { path = "../runtime" }
clap.workspace = true

[dev-dependencies]
